# Cổng chạy ứng dụng (Mặc định là 8080)
server.port=8080

# Cấu hình kết nối MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/smart_stadium?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=15072005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình Hibernate / JPA (Tự động cập nhật cấu trúc bảng từ các Entity Java)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect